/**
 * IUC IPGS Admission V2 - Management Intelligence Agent
 *
 * Cross-module operational intelligence. Read-mostly by design.
 * It does not make academic decisions or mutate student stages.
 */

const V2_MANAGEMENT_SNAPSHOT_SHEET='V2_MANAGEMENT_INTELLIGENCE';
const V2_MANAGEMENT_HEADERS=[
  'Snapshot ID','Generated At','Window','Applications Total','Applications Today',
  'Applications Yesterday','Applications 7D','Applications This Month','Applications 30D',
  'Open Human Tasks','High Priority Human Tasks',
  'Human Tasks >24H','Failed Agent Executions','Running Agent Executions',
  'Document Quality Follow-up','Screening Pending','SAC Waiting','IA Waiting',
  'Prerequisite Waiting','SKY Activation Pending','Orientation Upcoming 7D',
  'Orientation Waiting','Provisioning In Progress','Handover Ready','Stuck Cases >24H',
  'Critical Signals JSON','Stage Counts JSON','Agent Counts JSON','Snapshot JSON',
  'AI Brief','AI Provider','AI Model','Notification Status','Notification Sent At','Generated By'
];

function v2ManagementEnsureFoundation_(){
  const ss=SpreadsheetApp.openById(CONFIG.spreadsheetId);
  let sheet=ss.getSheetByName(V2_MANAGEMENT_SNAPSHOT_SHEET);
  if(!sheet)sheet=ss.insertSheet(V2_MANAGEMENT_SNAPSHOT_SHEET);
  v2EnsureHeaders_(sheet,V2_MANAGEMENT_HEADERS);
  v2StyleHeader_(sheet,V2_MANAGEMENT_HEADERS.length);
  return sheet;
}

function v2RunManagementIntelligence_(data,actor){
  assertDevIdentity_();
  v2ManagementEnsureFoundation_();

  const input=data||{};
  const now=new Date();
  const nowMs=now.getTime();
  const dayMs=24*60*60*1000;
  const todayKey=Utilities.formatDate(now,CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM-dd');
  const yesterdayDate=new Date(nowMs-dayMs);
  const yesterdayKey=Utilities.formatDate(yesterdayDate,CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM-dd');
  const monthKey=Utilities.formatDate(now,CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM');

  const apps=v2Rows_('V2_APPLICATIONS');
  const workflows=v2Rows_('V2_WORKFLOW');
  const humanTasks=v2Rows_('V2_HUMAN_TASKS');
  const executions=v2Rows_('V2_AGENT_EXECUTIONS');
  const docReviews=v2Rows_('V2_DOCUMENT_REVIEW');
  const orientationSessions=v2Rows_('V2_ORIENTATION_SESSIONS');
  const orientationTracking=v2Rows_('V2_ORIENTATION_TRACKING');
  const provisioning=v2Rows_('V2_PROVISIONING');

  const appTs=function(row){
    return v2ManagementParseTime_(row['Timestamp']||row['Created At']||row['Submitted At']||row['Last Updated']);
  };
  const workflowTs=function(row){
    return v2ManagementParseTime_(row['Last Updated']||row['Updated At']||row['Timestamp']);
  };

  const openHuman=humanTasks.filter(function(row){
    return ['OPEN','WAITING_HUMAN','IN_REVIEW'].indexOf(String(row['Status']||'').toUpperCase())>=0;
  });
  const highPriority=openHuman.filter(function(row){
    return String(row['Priority']||'NORMAL').toUpperCase()==='HIGH';
  });
  const agedHuman=openHuman.filter(function(row){
    const ts=v2ManagementParseTime_(row['Created At']);
    return ts && nowMs-ts>=dayMs;
  });

  const failedExec=executions.filter(function(row){
    return ['FAILED','NEEDS_INVESTIGATION','ERROR'].indexOf(String(row['Status']||'').toUpperCase())>=0;
  });
  const runningExec=executions.filter(function(row){
    return String(row['Status']||'').toUpperCase()==='RUNNING';
  });

  const stageCounts={};
  workflows.forEach(function(row){
    const stage=String(row['Application Stage']||'UNKNOWN').toUpperCase()||'UNKNOWN';
    stageCounts[stage]=(stageCounts[stage]||0)+1;
  });

  const agentCounts={};
  const latestByAgent={};
  v2Rows_('V2_AGENT_EVENTS').forEach(function(row){
    const id=String(row['Agent ID']||'').toUpperCase();
    if(!id)return;
    latestByAgent[id]=row;
    agentCounts[id]=(agentCounts[id]||0)+1;
  });

  const qualityFollow=docReviews.filter(function(row){
    return ['FOLLOW_UP_REQUIRED','HUMAN_REVIEW_REQUIRED'].indexOf(String(row['AI Quality Status']||'').toUpperCase())>=0;
  }).length;

  const screeningPending=workflows.filter(function(row){
    const stage=String(row['Application Stage']||'').toUpperCase();
    return ['DOCUMENT_REVIEW','QUALIFICATION_SCREENING'].indexOf(stage)>=0 &&
      !/READY_FOR_SAC|ELIGIBLE_FOR_OFFER|REJECTED/.test(stage);
  }).length;

  const sacWaiting=workflows.filter(function(row){
    return ['READY_FOR_SAC','SAC_REVIEW'].indexOf(String(row['Application Stage']||'').toUpperCase())>=0;
  }).length;
  const iaWaiting=workflows.filter(function(row){
    return String(row['Application Stage']||'').toUpperCase()==='INTERNAL_ASSESSMENT';
  }).length;
  const prereqWaiting=workflows.filter(function(row){
    return String(row['Application Stage']||'').toUpperCase()==='PREREQUISITE';
  }).length;

  const skyPending=workflows.filter(function(row){
    const prospect=String(row['Prospect Status']||'').toUpperCase();
    const activation=String(row['SKY Activation Status']||'').toUpperCase();
    return ['PROSPECT_COMPLETED','PROSPECT_UPDATED'].indexOf(prospect)>=0 && activation!=='ACTIVATED';
  }).length;

  const upcomingOrientation=orientationSessions.filter(function(row){
    const start=typeof v2OrientationSessionStart_==='function'?v2OrientationSessionStart_(row):null;
    if(!start)return false;
    const diff=start.getTime()-nowMs;
    const status=String(row['Status']||'SCHEDULED').toUpperCase();
    return diff>=0 && diff<=7*dayMs && ['SCHEDULED','OPEN','ACTIVE'].indexOf(status)>=0;
  }).length;

  const orientationWaiting=orientationTracking.filter(function(row){
    const status=String(row['Attendance Status']||'NOT_UPDATED').toUpperCase();
    const handover=String(row['Academic Handover Status']||'NOT_READY').toUpperCase();
    return status!=='ATTENDED' || handover==='NOT_READY';
  }).length;

  const provisioningInProgress=provisioning.filter(function(row){
    const studentNotification=String(row['Student Notification Status']||'').toUpperCase();
    const allComplete=
      String(row['IT Email Status']||'').toUpperCase()==='COMPLETED' &&
      String(row['Moodle Status']||'').toUpperCase()==='COMPLETED' &&
      String(row['E-Library Status']||'').toUpperCase()==='COMPLETED' &&
      studentNotification==='SENT';
    return !allComplete;
  }).length;

  const handoverReady=workflows.filter(function(row){
    return String(row['Academic Handover Status']||'').toUpperCase()==='READY';
  }).length;

  const terminalStages=['ACTIVE_STUDENT','REJECTED','CLOSED','WITHDRAWN'];
  const stuck=workflows.filter(function(row){
    const stage=String(row['Application Stage']||'').toUpperCase();
    if(terminalStages.indexOf(stage)>=0)return false;
    const ts=workflowTs(row);
    return ts && nowMs-ts>=dayMs;
  });

  const signals=[];
  highPriority.forEach(function(row){
    signals.push({
      severity:'HIGH',
      type:'HUMAN_TASK',
      referenceNo:String(row['Reference No']||''),
      title:String(row['Title']||row['Task Type']||'High-priority human task'),
      ageHours:v2ManagementAgeHours_(row['Created At'],nowMs)
    });
  });
  failedExec.slice(-20).forEach(function(row){
    signals.push({
      severity:'HIGH',
      type:'AGENT_FAILURE',
      referenceNo:String(row['Reference No']||''),
      title:String(row['Requested Action']||'Agent execution failed'),
      executionId:String(row['Execution ID']||''),
      error:String(row['Error']||'')
    });
  });
  stuck.slice(0,30).forEach(function(row){
    signals.push({
      severity:'MEDIUM',
      type:'STUCK_CASE',
      referenceNo:String(row['Reference No']||''),
      title:'Case unchanged for more than 24 hours',
      stage:String(row['Application Stage']||''),
      ageHours:v2ManagementAgeHours_(row['Last Updated']||row['Updated At'],nowMs)
    });
  });

  signals.sort(function(a,b){
    const rank={HIGH:3,MEDIUM:2,LOW:1};
    return (rank[b.severity]||0)-(rank[a.severity]||0);
  });

  const appToday=apps.filter(function(row){
    const ts=appTs(row);
    return ts && Utilities.formatDate(new Date(ts),CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM-dd')===todayKey;
  }).length;
  const appYesterday=apps.filter(function(row){
    const ts=appTs(row);
    return ts && Utilities.formatDate(new Date(ts),CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM-dd')===yesterdayKey;
  }).length;
  const app7=apps.filter(function(row){const ts=appTs(row);return ts&&nowMs-ts<=7*dayMs;}).length;
  const appMonth=apps.filter(function(row){
    const ts=appTs(row);
    return ts && Utilities.formatDate(new Date(ts),CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM')===monthKey;
  }).length;
  const app30=apps.filter(function(row){const ts=appTs(row);return ts&&nowMs-ts<=30*dayMs;}).length;

  const snapshot={
    generatedAt:now.toISOString(),
    applications:{total:apps.length,today:appToday,yesterday:appYesterday,last7Days:app7,thisMonth:appMonth,last30Days:app30},
    humanTasks:{open:openHuman.length,highPriority:highPriority.length,over24Hours:agedHuman.length},
    agentExecutions:{failed:failedExec.length,running:runningExec.length},
    queues:{
      documentQualityFollowUp:qualityFollow,
      screeningPending:screeningPending,
      sacWaiting:sacWaiting,
      iaWaiting:iaWaiting,
      prerequisiteWaiting:prereqWaiting,
      skyActivationPending:skyPending,
      orientationUpcoming7Days:upcomingOrientation,
      orientationWaiting:orientationWaiting,
      provisioningInProgress:provisioningInProgress,
      handoverReady:handoverReady,
      stuckCasesOver24Hours:stuck.length
    },
    stageCounts:stageCounts,
    agentCounts:agentCounts,
    criticalSignals:signals.slice(0,50)
  };

  const intelligence=v2ManagementGenerateBrief_(snapshot);
  const sendEmail=input.sendEmail===true || String(input.sendEmail||'').toUpperCase()==='TRUE';
  const notification=sendEmail
    ? v2ManagementSendDailyBrief_(snapshot,intelligence.brief,input)
    : {sent:false,status:'NOT_REQUESTED',recipients:[]};

  const id='MI-'+Utilities.formatDate(now,CONFIG.timezone||'Asia/Kuala_Lumpur','yyyyMMdd-HHmmss');
  v2Append_(V2_MANAGEMENT_SNAPSHOT_SHEET,{
    'Snapshot ID':id,
    'Generated At':snapshot.generatedAt,
    'Window':String(input.window||'LIVE'),
    'Applications Total':apps.length,
    'Applications Today':appToday,
    'Applications Yesterday':appYesterday,
    'Applications 7D':app7,
    'Applications This Month':appMonth,
    'Applications 30D':app30,
    'Open Human Tasks':openHuman.length,
    'High Priority Human Tasks':highPriority.length,
    'Human Tasks >24H':agedHuman.length,
    'Failed Agent Executions':failedExec.length,
    'Running Agent Executions':runningExec.length,
    'Document Quality Follow-up':qualityFollow,
    'Screening Pending':screeningPending,
    'SAC Waiting':sacWaiting,
    'IA Waiting':iaWaiting,
    'Prerequisite Waiting':prereqWaiting,
    'SKY Activation Pending':skyPending,
    'Orientation Upcoming 7D':upcomingOrientation,
    'Orientation Waiting':orientationWaiting,
    'Provisioning In Progress':provisioningInProgress,
    'Handover Ready':handoverReady,
    'Stuck Cases >24H':stuck.length,
    'Critical Signals JSON':JSON.stringify(signals.slice(0,50)),
    'Stage Counts JSON':JSON.stringify(stageCounts),
    'Agent Counts JSON':JSON.stringify(agentCounts),
    'Snapshot JSON':JSON.stringify(snapshot),
    'AI Brief':intelligence.brief,
    'AI Provider':intelligence.provider,
    'AI Model':intelligence.model,
    'Notification Status':String(notification.status||''),
    'Notification Sent At':notification.sent?now.toISOString():'',
    'Generated By':String(actor||'Management Intelligence Agent')
  });

  if(typeof v2EmitAgentEvent_==='function'){
    try{
      v2EmitAgentEvent_({
        referenceNo:'',
        eventType:'MANAGEMENT_INTELLIGENCE_REFRESHED',
        agentId:'MANAGEMENT_INTELLIGENCE',
        agentName:'Management Intelligence Agent',
        action:'OPERATIONS_SCAN',
        status:signals.some(function(x){return x.severity==='HIGH';})?'WAITING':'COMPLETED',
        requiresHuman:false,
        source:'N8N',
        summary:'Operations scan complete: '+openHuman.length+' open human task(s), '+failedExec.length+' failed execution(s), '+stuck.length+' case(s) unchanged >24h.'+(notification.sent?' Daily brief sent.':''),
        data:{
          snapshotId:id,
          highPrioritySignals:signals.filter(function(x){return x.severity==='HIGH';}).length
        }
      });
    }catch(_){}
  }

  v2InvalidateCache_();
  return {
    ok:true,
    snapshotId:id,
    snapshot:snapshot,
    aiBrief:intelligence.brief,
    aiProvider:intelligence.provider,
    aiModel:intelligence.model,
    notification:notification
  };
}

function v2ManagementGenerateBrief_(snapshot){
  const props=PropertiesService.getScriptProperties();
  const apiKey=String(props.getProperty('OPENAI_API_KEY')||'').trim();
  const model=String(props.getProperty('V2_MANAGEMENT_AI_MODEL')||props.getProperty('V2_AI_MODEL')||'gpt-5.6-luna').trim();

  const a=snapshot.applications||{};
  const q=snapshot.queues||{};
  const h=snapshot.humanTasks||{};
  const e=snapshot.agentExecutions||{};
  const fallback=[
    'Applications: '+(a.yesterday||0)+' yesterday, '+(a.last7Days||0)+' in the last 7 days, and '+(a.thisMonth||0)+' this month.',
    'Operational queue: '+(h.open||0)+' human task(s), '+(e.failed||0)+' failed execution(s), and '+(q.stuckCasesOver24Hours||0)+' case(s) unchanged for more than 24 hours.',
    'Pipeline: '+(q.sacWaiting||0)+' at SAC, '+((q.iaWaiting||0)+(q.prerequisiteWaiting||0))+' in IA/prerequisite, '+(q.handoverReady||0)+' ready for academic handover.'
  ].join(' ');

  if(!apiKey)return {brief:fallback,provider:'DETERMINISTIC_FALLBACK',model:''};

  try{
    const schema={
      type:'object',
      additionalProperties:false,
      properties:{brief:{type:'string'}},
      required:['brief']
    };
    const response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{
      method:'post',
      contentType:'application/json',
      headers:{Authorization:'Bearer '+apiKey},
      payload:JSON.stringify({
        model:model,
        store:false,
        reasoning:{effort:'low'},
        instructions:'You are the IUC IPGS Management Intelligence Agent. Summarise the supplied operational admission metrics for management in a concise factual brief. Highlight concrete queues, failures, stuck cases and immediate operational attention. Never invent facts and never make academic admission decisions.',
        input:[{role:'user',content:[{type:'input_text',text:JSON.stringify(snapshot)}]}],
        text:{format:{type:'json_schema',name:'iuc_management_brief',strict:true,schema:schema}}
      }),
      muteHttpExceptions:true
    });
    const status=response.getResponseCode();
    if(status<200||status>=300)throw new Error('OPENAI_MANAGEMENT_HTTP_'+status);
    const raw=JSON.parse(response.getContentText());
    const output=v2AiExtractResponseText_(raw);
    if(!output)throw new Error('No output_text');
    const parsed=JSON.parse(output);
    return {brief:String(parsed.brief||fallback),provider:'OPENAI',model:model};
  }catch(error){
    return {brief:fallback,provider:'DETERMINISTIC_FALLBACK',model:'',error:String(error&&error.message||error)};
  }
}

function v2ManagementSendDailyBrief_(snapshot,brief,input){
  const props=PropertiesService.getScriptProperties();
  const raw=String(input.recipients||props.getProperty('V2_MANAGEMENT_REPORT_EMAILS')||'').trim();
  const recipients=raw.split(/[;,\\s]+/).map(function(x){return x.trim();}).filter(Boolean);
  if(!recipients.length)return {sent:false,status:'SKIPPED_NO_RECIPIENT',recipients:[]};
  if(typeof v2NotificationSend_!=='function')return {sent:false,status:'NOTIFICATION_ENGINE_UNAVAILABLE',recipients:[]};

  const a=snapshot.applications||{};
  const q=snapshot.queues||{};
  const h=snapshot.humanTasks||{};
  const e=snapshot.agentExecutions||{};
  const date=Utilities.formatDate(new Date(snapshot.generatedAt),CONFIG.timezone||'Asia/Kuala_Lumpur','dd MMM yyyy');
  const subject='[IUC IPGS] Daily Admission Management Brief - '+date;
  const textBody=
    brief+'\n\n'+
    'Applications: '+(a.yesterday||0)+' yesterday / '+(a.last7Days||0)+' last 7 days / '+(a.thisMonth||0)+' this month\n'+
    'Open human tasks: '+(h.open||0)+'\n'+
    'Failed executions: '+(e.failed||0)+'\n'+
    'Stuck >24h: '+(q.stuckCasesOver24Hours||0)+'\n'+
    'Ready for SAC: '+(q.sacWaiting||0)+'\n'+
    'Handover ready: '+(q.handoverReady||0);

  const row=function(label,value){
    return '<tr><td style="padding:8px 10px;border-bottom:1px solid #eceef3;color:#5d6575">'+v2Html_(label)+'</td>'+
      '<td style="padding:8px 10px;border-bottom:1px solid #eceef3;text-align:right;font-weight:700">'+v2Html_(String(value))+'</td></tr>';
  };
  const html=
    '<div style="font-family:Arial,sans-serif;max-width:720px;margin:auto;border:1px solid #e5e7eb;border-radius:16px;overflow:hidden">'+
    '<div style="background:#2d2363;color:white;padding:22px"><h2 style="margin:0">Daily Admission Management Brief</h2><div style="margin-top:5px;opacity:.82">'+v2Html_(date)+'</div></div>'+
    '<div style="padding:24px"><p style="line-height:1.65">'+v2Html_(brief)+'</p>'+
    '<table style="width:100%;border-collapse:collapse;font-size:13px">'+
      row('Applications yesterday',a.yesterday||0)+
      row('Applications last 7 days',a.last7Days||0)+
      row('Applications this month',a.thisMonth||0)+
      row('Open human tasks',h.open||0)+
      row('High-priority human tasks',h.highPriority||0)+
      row('Failed agent executions',e.failed||0)+
      row('Stuck cases >24h',q.stuckCasesOver24Hours||0)+
      row('Document quality follow-up',q.documentQualityFollowUp||0)+
      row('Ready / waiting SAC',q.sacWaiting||0)+
      row('IA / prerequisite',(q.iaWaiting||0)+(q.prerequisiteWaiting||0))+
      row('SKY activation pending',q.skyActivationPending||0)+
      row('Orientation waiting',q.orientationWaiting||0)+
      row('Academic handover ready',q.handoverReady||0)+
    '</table></div></div>';

  return v2NotificationSend_('MANAGEMENT_DAILY_BRIEF',recipients,subject,textBody,html,{
    senderName:'IUC IPGS Management Intelligence'
  });
}

function v2ManagementAgeHours_(value,nowMs){
  const ts=v2ManagementParseTime_(value);
  if(!ts)return 0;
  return Math.max(0,Math.round(((nowMs||Date.now())-ts)/3600000));
}

function v2ManagementParseTime_(value){
  const raw=String(value||'').trim();
  if(!raw)return 0;
  const d=new Date(raw);
  if(!isNaN(d.getTime()))return d.getTime();
  return 0;
}
