/**
 * IUC IPGS Admission V2 - Management Intelligence Agent
 *
 * Cross-module operational intelligence. Read-mostly by design.
 * It does not make academic decisions or mutate student stages.
 */

const V2_MANAGEMENT_SNAPSHOT_SHEET='V2_MANAGEMENT_INTELLIGENCE';
const V2_MANAGEMENT_HEADERS=[
  'Snapshot ID','Generated At','Window','Applications Total','Applications Today',
  'Applications 7D','Applications 30D','Open Human Tasks','High Priority Human Tasks',
  'Human Tasks >24H','Failed Agent Executions','Running Agent Executions',
  'Document Quality Follow-up','Screening Pending','SAC Waiting','IA Waiting',
  'Prerequisite Waiting','SKY Activation Pending','Orientation Upcoming 7D',
  'Orientation Waiting','Provisioning In Progress','Handover Ready','Stuck Cases >24H',
  'Critical Signals JSON','Stage Counts JSON','Agent Counts JSON','Snapshot JSON',
  'Generated By'
];

function v2ManagementEnsureFoundation_(){
  const ss=SpreadsheetApp.openById(CONFIG.spreadsheetId);
  let sheet=ss.getSheetByName(V2_MANAGEMENT_SNAPSHOT_SHEET);
  if(!sheet)sheet=ss.insertSheet(V2_MANAGEMENT_SNAPSHOT_SHEET);
  v2EnsureHeaders_(sheet,V2_MANAGEMENT_HEADERS);
  v2StyleHeader_(sheet,V2_MANAGEMENT_HEADERS.length);
  return sheet;
}

function v2RunManagementIntelligence_(data,actor){
  assertDevIdentity_();
  v2ManagementEnsureFoundation_();

  const input=data||{};
  const now=new Date();
  const nowMs=now.getTime();
  const dayMs=24*60*60*1000;
  const todayKey=Utilities.formatDate(now,CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM-dd');

  const apps=v2Rows_('V2_APPLICATIONS');
  const workflows=v2Rows_('V2_WORKFLOW');
  const humanTasks=v2Rows_('V2_HUMAN_TASKS');
  const executions=v2Rows_('V2_AGENT_EXECUTIONS');
  const docReviews=v2Rows_('V2_DOCUMENT_REVIEW');
  const orientationSessions=v2Rows_('V2_ORIENTATION_SESSIONS');
  const orientationTracking=v2Rows_('V2_ORIENTATION_TRACKING');
  const provisioning=v2Rows_('V2_PROVISIONING');

  const appTs=function(row){
    return v2ManagementParseTime_(row['Timestamp']||row['Created At']||row['Submitted At']||row['Last Updated']);
  };
  const workflowTs=function(row){
    return v2ManagementParseTime_(row['Last Updated']||row['Updated At']||row['Timestamp']);
  };

  const openHuman=humanTasks.filter(function(row){
    return ['OPEN','WAITING_HUMAN','IN_REVIEW'].indexOf(String(row['Status']||'').toUpperCase())>=0;
  });
  const highPriority=openHuman.filter(function(row){
    return String(row['Priority']||'NORMAL').toUpperCase()==='HIGH';
  });
  const agedHuman=openHuman.filter(function(row){
    const ts=v2ManagementParseTime_(row['Created At']);
    return ts && nowMs-ts>=dayMs;
  });

  const failedExec=executions.filter(function(row){
    return ['FAILED','NEEDS_INVESTIGATION','ERROR'].indexOf(String(row['Status']||'').toUpperCase())>=0;
  });
  const runningExec=executions.filter(function(row){
    return String(row['Status']||'').toUpperCase()==='RUNNING';
  });

  const stageCounts={};
  workflows.forEach(function(row){
    const stage=String(row['Application Stage']||'UNKNOWN').toUpperCase()||'UNKNOWN';
    stageCounts[stage]=(stageCounts[stage]||0)+1;
  });

  const agentCounts={};
  const latestByAgent={};
  v2Rows_('V2_AGENT_EVENTS').forEach(function(row){
    const id=String(row['Agent ID']||'').toUpperCase();
    if(!id)return;
    latestByAgent[id]=row;
    agentCounts[id]=(agentCounts[id]||0)+1;
  });

  const qualityFollow=docReviews.filter(function(row){
    return ['FOLLOW_UP_REQUIRED','HUMAN_REVIEW_REQUIRED'].indexOf(String(row['AI Quality Status']||'').toUpperCase())>=0;
  }).length;

  const screeningPending=workflows.filter(function(row){
    const stage=String(row['Application Stage']||'').toUpperCase();
    return ['DOCUMENT_REVIEW','QUALIFICATION_SCREENING'].indexOf(stage)>=0 &&
      !/READY_FOR_SAC|ELIGIBLE_FOR_OFFER|REJECTED/.test(stage);
  }).length;

  const sacWaiting=workflows.filter(function(row){
    return ['READY_FOR_SAC','SAC_REVIEW'].indexOf(String(row['Application Stage']||'').toUpperCase())>=0;
  }).length;
  const iaWaiting=workflows.filter(function(row){
    return String(row['Application Stage']||'').toUpperCase()==='INTERNAL_ASSESSMENT';
  }).length;
  const prereqWaiting=workflows.filter(function(row){
    return String(row['Application Stage']||'').toUpperCase()==='PREREQUISITE';
  }).length;

  const skyPending=workflows.filter(function(row){
    const prospect=String(row['Prospect Status']||'').toUpperCase();
    const activation=String(row['SKY Activation Status']||'').toUpperCase();
    return ['PROSPECT_COMPLETED','PROSPECT_UPDATED'].indexOf(prospect)>=0 && activation!=='ACTIVATED';
  }).length;

  const upcomingOrientation=orientationSessions.filter(function(row){
    const start=typeof v2OrientationSessionStart_==='function'?v2OrientationSessionStart_(row):null;
    if(!start)return false;
    const diff=start.getTime()-nowMs;
    const status=String(row['Status']||'SCHEDULED').toUpperCase();
    return diff>=0 && diff<=7*dayMs && ['SCHEDULED','OPEN','ACTIVE'].indexOf(status)>=0;
  }).length;

  const orientationWaiting=orientationTracking.filter(function(row){
    const status=String(row['Attendance Status']||'NOT_UPDATED').toUpperCase();
    const handover=String(row['Academic Handover Status']||'NOT_READY').toUpperCase();
    return status!=='ATTENDED' || handover==='NOT_READY';
  }).length;

  const provisioningInProgress=provisioning.filter(function(row){
    const studentNotification=String(row['Student Notification Status']||'').toUpperCase();
    const allComplete=
      String(row['IT Email Status']||'').toUpperCase()==='COMPLETED' &&
      String(row['Moodle Status']||'').toUpperCase()==='COMPLETED' &&
      String(row['E-Library Status']||'').toUpperCase()==='COMPLETED' &&
      studentNotification==='SENT';
    return !allComplete;
  }).length;

  const handoverReady=workflows.filter(function(row){
    return String(row['Academic Handover Status']||'').toUpperCase()==='READY';
  }).length;

  const terminalStages=['ACTIVE_STUDENT','REJECTED','CLOSED','WITHDRAWN'];
  const stuck=workflows.filter(function(row){
    const stage=String(row['Application Stage']||'').toUpperCase();
    if(terminalStages.indexOf(stage)>=0)return false;
    const ts=workflowTs(row);
    return ts && nowMs-ts>=dayMs;
  });

  const signals=[];
  highPriority.forEach(function(row){
    signals.push({
      severity:'HIGH',
      type:'HUMAN_TASK',
      referenceNo:String(row['Reference No']||''),
      title:String(row['Title']||row['Task Type']||'High-priority human task'),
      ageHours:v2ManagementAgeHours_(row['Created At'],nowMs)
    });
  });
  failedExec.slice(-20).forEach(function(row){
    signals.push({
      severity:'HIGH',
      type:'AGENT_FAILURE',
      referenceNo:String(row['Reference No']||''),
      title:String(row['Requested Action']||'Agent execution failed'),
      executionId:String(row['Execution ID']||''),
      error:String(row['Error']||'')
    });
  });
  stuck.slice(0,30).forEach(function(row){
    signals.push({
      severity:'MEDIUM',
      type:'STUCK_CASE',
      referenceNo:String(row['Reference No']||''),
      title:'Case unchanged for more than 24 hours',
      stage:String(row['Application Stage']||''),
      ageHours:v2ManagementAgeHours_(row['Last Updated']||row['Updated At'],nowMs)
    });
  });

  signals.sort(function(a,b){
    const rank={HIGH:3,MEDIUM:2,LOW:1};
    return (rank[b.severity]||0)-(rank[a.severity]||0);
  });

  const appToday=apps.filter(function(row){
    const ts=appTs(row);
    return ts && Utilities.formatDate(new Date(ts),CONFIG.timezone||'Asia/Kuala_Lumpur','yyyy-MM-dd')===todayKey;
  }).length;
  const app7=apps.filter(function(row){const ts=appTs(row);return ts&&nowMs-ts<=7*dayMs;}).length;
  const app30=apps.filter(function(row){const ts=appTs(row);return ts&&nowMs-ts<=30*dayMs;}).length;

  const snapshot={
    generatedAt:now.toISOString(),
    applications:{total:apps.length,today:appToday,last7Days:app7,last30Days:app30},
    humanTasks:{open:openHuman.length,highPriority:highPriority.length,over24Hours:agedHuman.length},
    agentExecutions:{failed:failedExec.length,running:runningExec.length},
    queues:{
      documentQualityFollowUp:qualityFollow,
      screeningPending:screeningPending,
      sacWaiting:sacWaiting,
      iaWaiting:iaWaiting,
      prerequisiteWaiting:prereqWaiting,
      skyActivationPending:skyPending,
      orientationUpcoming7Days:upcomingOrientation,
      orientationWaiting:orientationWaiting,
      provisioningInProgress:provisioningInProgress,
      handoverReady:handoverReady,
      stuckCasesOver24Hours:stuck.length
    },
    stageCounts:stageCounts,
    agentCounts:agentCounts,
    criticalSignals:signals.slice(0,50)
  };

  const id='MI-'+Utilities.formatDate(now,CONFIG.timezone||'Asia/Kuala_Lumpur','yyyyMMdd-HHmmss');
  v2Append_(V2_MANAGEMENT_SNAPSHOT_SHEET,{
    'Snapshot ID':id,
    'Generated At':snapshot.generatedAt,
    'Window':String(input.window||'LIVE'),
    'Applications Total':apps.length,
    'Applications Today':appToday,
    'Applications 7D':app7,
    'Applications 30D':app30,
    'Open Human Tasks':openHuman.length,
    'High Priority Human Tasks':highPriority.length,
    'Human Tasks >24H':agedHuman.length,
    'Failed Agent Executions':failedExec.length,
    'Running Agent Executions':runningExec.length,
    'Document Quality Follow-up':qualityFollow,
    'Screening Pending':screeningPending,
    'SAC Waiting':sacWaiting,
    'IA Waiting':iaWaiting,
    'Prerequisite Waiting':prereqWaiting,
    'SKY Activation Pending':skyPending,
    'Orientation Upcoming 7D':upcomingOrientation,
    'Orientation Waiting':orientationWaiting,
    'Provisioning In Progress':provisioningInProgress,
    'Handover Ready':handoverReady,
    'Stuck Cases >24H':stuck.length,
    'Critical Signals JSON':JSON.stringify(signals.slice(0,50)),
    'Stage Counts JSON':JSON.stringify(stageCounts),
    'Agent Counts JSON':JSON.stringify(agentCounts),
    'Snapshot JSON':JSON.stringify(snapshot),
    'Generated By':String(actor||'Management Intelligence Agent')
  });

  if(typeof v2EmitAgentEvent_==='function'){
    try{
      v2EmitAgentEvent_({
        referenceNo:'',
        eventType:'MANAGEMENT_INTELLIGENCE_REFRESHED',
        agentId:'MANAGEMENT_INTELLIGENCE',
        agentName:'Management Intelligence Agent',
        action:'OPERATIONS_SCAN',
        status:signals.some(function(x){return x.severity==='HIGH';})?'WAITING':'COMPLETED',
        requiresHuman:false,
        source:'N8N',
        summary:'Operations scan complete: '+openHuman.length+' open human task(s), '+failedExec.length+' failed execution(s), '+stuck.length+' case(s) unchanged >24h.',
        data:{
          snapshotId:id,
          highPrioritySignals:signals.filter(function(x){return x.severity==='HIGH';}).length
        }
      });
    }catch(_){}
  }

  v2InvalidateCache_();
  return {ok:true,snapshotId:id,snapshot:snapshot};
}

function v2ManagementAgeHours_(value,nowMs){
  const ts=v2ManagementParseTime_(value);
  if(!ts)return 0;
  return Math.max(0,Math.round(((nowMs||Date.now())-ts)/3600000));
}

function v2ManagementParseTime_(value){
  const raw=String(value||'').trim();
  if(!raw)return 0;
  const d=new Date(raw);
  if(!isNaN(d.getTime()))return d.getTime();
  return 0;
}
