import{BY_ID}from'./config.js';
const el=id=>document.getElementById(id);const pretty=s=>String(s||'').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
export class ActivityHUD{
 constructor(engine,scene){this.engine=engine;this.scene=scene;this.selected=engine.apps[0];this.events=[];this.last=0;this.metricSig='';this.selectionSig='';this.rosterSig='';this.bind();this.select(this.selected);}
 select(a){if(this.selected)this.selected.selected=false;this.selected=a;if(a){a.selected=true;this.scene.selected=a;}else this.scene.selected=null;this.selectionSig='';this.rosterSig='';this.render(true);}
 event(e){this.events.unshift(e);this.events=this.events.slice(0,60);const host=el('activity');if(!host?.closest('details')?.open)return;const row=document.createElement('div'),time=document.createElement('time'),body=document.createElement('span');time.textContent=this.clock(e.time);body.textContent=(e.app?.name?e.app.name+' · ':'')+e.action;row.append(time,body);host.prepend(row);while(host.children.length>60)host.lastChild.remove();}
 clock(sec){return new Date(new Date().setHours(10,24,0,0)+sec*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
 toast(message){el('toast').textContent=message;el('toast').classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el('toast').classList.remove('visible'),4000);}
 bind(){el('pause').onclick=()=>{this.engine.paused=!this.engine.paused;el('pause').textContent=this.engine.paused?'▶ Resume':'Ⅱ Pause';};el('add').onclick=()=>{this.toast(this.engine.add()?'Applicant joined the reception queue':'Demo limit: 30 applicants');this.render(true);};el('sac').onclick=()=>this.toast(this.engine.conveneSac()?'SAC session convened':'SAC requires seated waiting applicants and an available committee');el('orientation').onclick=()=>this.toast(this.engine.orientation.start()?'The orientation cohort is starting':'No seated cohort is ready, or a session is still active');el('speed').onchange=e=>this.engine.speed=Number(e.target.value);el('follow').onclick=()=>{this.scene.follow=!this.scene.follow;if(this.scene.follow&&this.selected)this.scene.focus(this.selected);};el('map').onclick=()=>this.scene.fullMap();el('plus').onclick=()=>this.scene.camera.zoom=Math.min(1.65,this.scene.camera.zoom*1.2);el('minus').onclick=()=>this.scene.camera.zoom=Math.max(.17,this.scene.camera.zoom/1.2);el('hide').onclick=()=>{el('hud').hidden=true;el('showHud').hidden=false;};el('showHud').onclick=()=>{el('hud').hidden=false;el('showHud').hidden=true;};this.scene.onSelect=a=>this.select(a);this.scene.onRoom=s=>this.toast(`${s.label} · ${s.processingMode} · capacity ${s.capacity} · ${s.tasks.length} task agents`);const details=el('roster')?.closest('details');details?.addEventListener('toggle',()=>{this.rosterSig='';this.render(true);});}
 render(force=false){const e=this.engine,a=this.selected,wait=e.live?900:350;if(!force&&performance.now()-this.last<wait)return;this.last=performance.now();el('mode').textContent=e.live?'Live ACC':'Simulation';el('count').textContent=`(${e.apps.length})`;
 const metrics=[['New',e.apps.filter(a=>a.status==='WAITING_NEW_APPLICATION').length],['In progress',e.apps.filter(a=>['PROCESSING','PROVISIONING','HANDOVER'].includes(a.status)).length],['Orientation',e.apps.filter(a=>a.station==='orientation'&&a.status!=='COMPLETED').length],['Completed',e.apps.filter(a=>a.status==='COMPLETED').length]],metricSig=metrics.flat().join('|');if(metricSig!==this.metricSig){this.metricSig=metricSig;el('metrics').replaceChildren(...metrics.map(([label,value])=>{let d=document.createElement('div'),b=document.createElement('b'),s=document.createElement('small');b.textContent=value;s.textContent=label;d.append(b,s);return d;}));}
 const selection=el('selection'),selectionSig=a?[a.id,a.name,a.status,a.station,a.reason,a.task,a.waitingSince,a.next,e.live].join('|'):'none';if(force||selectionSig!==this.selectionSig){this.selectionSig=selectionSig;selection.replaceChildren();if(a){const h=document.createElement('h2'),id=document.createElement('div'),state=document.createElement('div'),dl=document.createElement('dl');h.textContent=a.name;id.className='id';id.textContent=a.id;state.className='state';state.textContent=pretty(a.status);const pairs=[['Location',BY_ID[a.station]?.label||'Campus'],['Reason',a.reason||'Staff workstation'],['Task agent',a.task||'Campus staff'],['Verification',e.live?'Live ACC snapshot · read only':'Simulated workflow · no emails or accounts created'],['Next',BY_ID[a.next]?.label||'—']];if(a.status.startsWith('WAITING'))pairs.splice(2,0,['Waiting since',a.live?(a.waitingSince||'Not supplied'):this.clock(a.waitingSince||0)]);for(const[k,v]of pairs){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;dl.append(dt,dd);}selection.append(id,h,state,dl);if(!e.live&&!a.isStaff&&a.status!=='COMPLETED'){let b=document.createElement('button');b.style.marginTop='12px';b.textContent=a.held?'Release human hold':'Simulate human hold';b.onclick=()=>{e.hold(a);this.render(true);};selection.append(b);}}}
 const roster=el('roster'),details=roster?.closest('details');if(details?.open){const rosterSig=e.apps.map(app=>`${app.id}:${app.status}:${app.station}`).join('|')+'|'+(a?.id||'');if(force||rosterSig!==this.rosterSig){this.rosterSig=rosterSig;roster.replaceChildren(...e.apps.map(app=>{const b=document.createElement('button');b.className='app'+(a===app?' selected':'');const avatar=document.createElement('span'),label=document.createElement('span'),name=document.createElement('b'),status=document.createElement('small');avatar.className='avatar';avatar.textContent=app.name.slice(0,2);name.textContent=app.name;status.textContent=app.status==='WAITING_NEW_APPLICATION'?'Admission queue':pretty(app.status)+' · '+(BY_ID[app.station]?.label||'');label.append(name,status);b.append(avatar,label);b.onclick=()=>{this.select(app);this.scene.focus(app);};return b;}));}}else if(roster?.childElementCount){roster.replaceChildren();this.rosterSig='';}
 for(const id of ['pause','add','sac','orientation','speed'])el(id).disabled=e.live;el('follow').classList.toggle('active',this.scene.follow);
 }
}