export class OrientationSession{
 constructor(engine){this.engine=engine;this.phase='waiting';this.cohort=[];this.remaining=0;this.serial=0;}
 start(){const e=this.engine;if(this.phase!=='waiting')return false;const ready=e.apps.filter(a=>a.status==='WAITING_ORIENTATION'&&!a.path.length);if(!ready.length)return false;this.cohort=[...ready];this.serial++;this.phase='session';this.remaining=15;for(const a of ready){a.status='ORIENTATION_IN_PROGRESS';a.task='Orientation Attendance Agent';a.reason='Attending the scheduled cohort session';}e.emit('ORIENTATION_IN_PROGRESS',ready[0],`${ready.length} students · cohort ${this.serial}`);e.screen('ORIENTATION IN PROGRESS',`${ready.length} students · Welcome to IUC`);return true;}
 update(dt){if(['waiting','moving'].includes(this.phase))return;this.remaining-=dt;if(this.remaining>0)return;const e=this.engine;
 if(this.phase==='session'){this.phase='followup';this.remaining=8;e.screen('ORIENTATION COMPLETED','Recording · feedback · community links');for(const a of this.cohort){a.status='FOLLOW_UP_PROCESSING';a.task='Orientation Follow-up Agent';a.reason='Preparing recording link, feedback and community information';}e.emit('FOLLOW_UP_PROCESSING',this.cohort[0],'Preparing recording and post-session information');}
 else if(this.phase==='followup'){e.emit('FOLLOW_UP_COMPLETE',this.cohort[0],'Simulated recording, feedback and community links prepared');this.phase='moving';const group=this.cohort;for(const a of group){e.release(a);a.cohort=this.serial;a.index=a.route.indexOf('services');a.next='services';a.status='WAITING_NEXT_STATION';a.reason='Cohort moving to Student Services';a.seat=null;}e.groupTransfer(group,'services',()=>{this.phase='services';this.remaining=14;});}
 else if(this.phase==='services'){for(const a of this.cohort){e.release(a);a.index=a.route.indexOf('handover');a.next='handover';}this.phase='moving';e.groupTransfer(this.cohort,'handover',()=>{this.phase='handover';this.remaining=10;});}
 else if(this.phase==='handover'){for(const a of this.cohort){e.release(a);a.status='COMPLETED';a.reason='Academic handover complete';a.task='Management Reporting Agent';e.emit('COMPLETED',a,'Admission-to-academic journey completed');}this.cohort=[];this.phase='waiting';e.screen('NEXT ORIENTATION','Waiting for the next cohort');}
 }
}
