import{STATIONS,BY_ID,ROUTES,DEMO}from'./config.js';import{Station}from'./Station.js';import{WaitingLounge}from'./WaitingLounge.js';import{ApplicantActor}from'./ApplicantActor.js';import{OrientationSession}from'./OrientationSession.js';
export class WorkflowEngine{
 constructor(scene,onEvent){this.scene=scene;this.onEvent=onEvent;this.stations=Object.fromEntries(STATIONS.map(s=>[s.id,new Station(s)]));this.lounge=new WaitingLounge(scene.loungeSeats);this.apps=[];this.clock=0;this.paused=false;this.speed=1;this.live=false;this.nextSac=35;this.sacActive=false;this.orientation=new OrientationSession(this);this.seed();}
 emit(type,a,action){this.onEvent?.({type,app:a,action,time:this.clock,agent:a?.task||'Admissions Coordinator'});}
 screen(title,sub){const p=this.scene.props.find(p=>p.dynamic==='orientation');if(p){p.title=title;p.sub=sub;}}
 make(name,route='direct'){const n=this.apps.length+1;const a=new ApplicantActor({id:`APP-${String(n).padStart(2,'0')}`,name,route:ROUTES[route],routeName:route,index:0,next:'admission',reason:'Waiting for Admission staff to call',waitingSince:this.clock},170,625+(n-1)%5*65,[5,2,3,4,5,2,3,5][(n-1)%8]);this.apps.push(a);return a;}
 seed(){DEMO.forEach(([n,r])=>this.make(n,r));this.scene.actors=this.apps;
 // A labelled demonstration opens with concurrent work already under way.
 for(const [i,station] of [[0,'screening'],[2,'document'],[3,'admission']]){let a=this.apps[i];a.index=a.route.indexOf(station);a.next=station;this.admit(a,true);}
 for(const i of [1,7]){let a=this.apps[i];a.index=a.route.indexOf('sac');a.next='sac';this.wait(a,'WAITING_SAC_SESSION','SAC session has not started',true);}
 for(const i of [5,6,8]){const a=this.apps[i];a.index=a.route.indexOf('orientation');a.next='orientation';this.admit(a,true);}
 this.requeue();this.emit('CAMPUS_OPEN',this.apps[0],'Demonstration: concurrent applications and a waiting orientation cohort');}
 requeue(){let i=0;for(const a of this.apps)if(a.status==='WAITING_NEW_APPLICATION'){a.x=130+(i%2)*65;a.y=620+Math.floor(i/2)*62;i++;}}
 add(){if(this.live||this.apps.length>=30)return false;const a=this.make(['Iman','Arif','Lina','Aisha','Faris'][this.apps.length%5],['direct','ia','prerequisite'][this.apps.length%3]);this.requeue();this.emit('APPLICATION_RECEIVED',a,'New applicant joined the reception queue');return true;}
 release(a){if(a.reserved)this.stations[a.reserved].release(a);a.reserved=null;this.lounge.release(a);}
 move(a,target,cb){try{a.moveTo(target,this.scene.nav,cb);}catch(err){this.release(a);a.status='WAITING_HUMAN_DECISION';a.reason='Navigation is unavailable; movement paused';a.moveError=err.message;this.emit('NAVIGATION_BLOCKED',a,err.message);}}
 wait(a,status,reason,instant=false){if(a.waitTarget===a.next&&a.status===status)return;a.status=status;a.reason=reason;a.waitingSince=this.clock;a.waitTarget=a.next;const seat=this.lounge.reserve(a);a.seat=seat;if(seat){const finish=()=>a.sit(a.profile%2?'phone':'reading');if(instant){const p=this.scene.nav.point(this.scene.nav.nearest(seat));a.x=p.x;a.y=p.y;finish();}else this.move(a,seat,finish);}else{a.reason+=' · lounge full; waiting at designated corridor bay';this.move(a,{x:330,y:1060+this.apps.indexOf(a)%6*45},()=>{a.pose='waiting';});}this.emit(status,a,reason);}
 target(a,s){if(s.id==='orientation'){let used=new Set(this.apps.filter(b=>b!==a&&b.orientationSeat!=null&&b.reserved==='orientation').map(b=>b.orientationSeat));let index=0;while(used.has(index))index++;a.orientationSeat=index;return this.scene.orientationSeats[index];}if(this.scene.stationSeats[s.id]){const slots=this.scene.stationSeats[s.id];return slots[(s.occupants.size-1)%slots.length];}return s.point;}
 admit(a,instant=false){const s=this.stations[a.next];if(!s?.reserve(a))return false;this.lounge.release(a);a.reserved=s.id;a.station=s.id;a.waitTarget=null;a.seat=null;a.reason='Walking to '+s.label;a.status=s.id==='orientation'?'WAITING_ORIENTATION':'PROCESSING';a.task=s.tasks[0];a.arrived=false;a.taskIndex=0;a.remaining=2.8;
 const target=this.target(a,s);const arrive=()=>{a.arrived=true;a.pose='idle';a.reason=s.id==='orientation'?'Invited; waiting for the scheduled group session':'Processing at '+s.label;if(['orientation','sac','ia','prerequisite','offer'].includes(s.id))a.sit();this.emit(s.id==='orientation'?'WAITING_ORIENTATION':'TASK_STARTED',a,a.reason);};
 const staff=this.scene.staff.find(st=>st.id.toLowerCase().includes(s.id==='document'?'document':s.id==='sac'?'sac':s.id==='ia'?'ia':s.label.split(' ')[0].toLowerCase()));!instant&&staff?.say(`${a.name}, ${s.id==='admission'?'next please!':'please take a seat.'}`,this.scene.time);
 if(instant){const p=this.scene.nav.point(this.scene.nav.nearest(target));a.x=p.x;a.y=p.y;arrive();}else{a.say(s.id==='orientation'?'Orientation will begin shortly.':`${s.label} is ready.`,this.scene.time);this.move(a,target,arrive);}return true;}
 complete(a){const old=a.station;this.release(a);a.index++;a.next=a.route[a.index];if(!a.next){a.status='COMPLETED';return;}a.arrived=false;a.status='WAITING_NEXT_STATION';a.waitTarget=null;a.waitingSince=this.clock;this.emit('STAGE_COMPLETE',a,BY_ID[old].label+' completed');
 if(old==='ia'&&a.next==='prerequisite'){a.say('Prerequisite required.',this.scene.time);this.emit('PREREQUISITE_REQUIRED',a,'IA outcome requires prerequisite; completion proceeds to LOA');}
 }
 conveneSac(){if(this.live||this.sacActive)return false;const waiting=this.apps.filter(a=>a.next==='sac'&&a.status==='WAITING_SAC_SESSION'&&!a.path.length&&!a.held).slice(0,this.stations.sac.capacity);if(!waiting.length)return false;this.sacActive=true;for(const a of waiting)this.admit(a);this.emit('SAC_SESSION_STARTED',waiting[0],`${waiting.length} applications in this SAC session`);this.nextSac=this.clock+65;return true;}
 groupTransfer(group,to,onReady){let arrived=0;const s=this.stations[to];for(let i=0;i<group.length;i++){let a=group[i];s.occupants.add(a.id);a.reserved=to;a.station=to;a.status=to==='services'?'PROVISIONING':'HANDOVER';a.task=s.tasks[0];a.reason='Moving with orientation cohort';const target={x:s.point.x+(i%6-2.5)*48,y:s.point.y+Math.floor(i/6)*42};this.move(a,target,()=>{a.reason=to==='services'?'IT, Library and Moodle account provisioning':'Academic handover, audit and reporting';a.pose='working';arrived++;if(arrived===group.length)onReady();});}
 const staff=this.scene.staff.find(s=>s.id==='Orientation presenter');if(staff&&!staff.path.length){staff.say('Cohort, this way please.',this.scene.time);this.move(staff,{x:s.door.x-45,y:s.door.y-60},()=>this.move(staff,staff.home,()=>staff.pose='idle'));}this.emit('COHORT_HANDOFF',group[0],`${group.length} students moving together to ${s.label}`);}
 hold(a){if(this.live||a.isStaff||['COMPLETED','ORIENTATION_IN_PROGRESS','FOLLOW_UP_PROCESSING','PROVISIONING','HANDOVER'].includes(a.status))return;if(a.held){a.held=false;a.status='WAITING_NEXT_STATION';a.waitTarget=null;a.reason='Human decision recorded in simulation';}else{this.release(a);a.path=[];a.onArrive=null;a.held=true;this.wait(a,'WAITING_HUMAN_DECISION','Requested evidence or human decision is pending');}}
 update(dt){if(this.paused||this.live)return;dt*=this.speed;this.clock+=dt;for(const a of [...this.apps,...this.scene.staff])a.update(dt);
 for(const a of this.apps){if(a.held||a.moveError)continue;if(a.status==='PROCESSING'&&a.arrived){a.remaining-=dt;if(a.remaining<=0){a.taskIndex++;const s=this.stations[a.station];if(a.taskIndex<s.tasks.length){a.task=s.tasks[a.taskIndex];a.remaining=2.8;this.emit('TASK_STARTED',a,a.task);}else this.complete(a);}}
 if(['WAITING_NEW_APPLICATION','WAITING_NEXT_STATION','WAITING_SAC_SESSION','WAITING_IA','WAITING_PREREQUISITE'].includes(a.status)&&!a.path.length){if(a.next==='sac'){this.wait(a,'WAITING_SAC_SESSION','SAC session has not started');continue;}const s=this.stations[a.next];if(a.next==='orientation'&&this.orientation.phase!=='waiting'){this.wait(a,'WAITING_NEXT_STATION','The current orientation cohort is still in session');continue;}if(s?.available)this.admit(a);else if(a.status!=='WAITING_NEW_APPLICATION')this.wait(a,a.next==='ia'?'WAITING_IA':a.next==='prerequisite'?'WAITING_PREREQUISITE':'WAITING_NEXT_STATION',s?.label+' is currently occupied');}
 }
 if(this.sacActive&&!this.stations.sac.occupants.size)this.sacActive=false;if(this.clock>=this.nextSac&&!this.sacActive)this.conveneSac();this.orientation.update(dt);
 // Provisioning task names reflect the current cohort phase rather than fake backend actions.
 if(this.orientation.phase==='services'){const idx=Math.min(2,Math.floor((14-this.orientation.remaining)/4.7));for(const a of this.orientation.cohort)a.task=BY_ID.services.tasks[idx];}if(this.orientation.phase==='handover'){const idx=Math.min(3,Math.floor((10-this.orientation.remaining)/2.5));for(const a of this.orientation.cohort)a.task=BY_ID.handover.tasks[idx];}
 }
}
