from pathlib import Path
import re

p = Path('admin.html')
s = p.read_text(encoding='utf-8')

marker = '/* PHASE2_MOBILE_POLISH_V2 */'
if marker not in s:
    css = r'''
    /* PHASE2_MOBILE_POLISH_V2 */
    .screening-stack{display:grid;gap:12px;width:100%}.screening-section{border:1px solid var(--line);border-radius:15px;background:#fff;padding:13px}.screening-section .screening-title{font-size:12px;font-weight:900;color:#282059;margin-bottom:4px}.screening-section .screening-help{font-size:11px;color:#7a8191;line-height:1.45;margin-bottom:10px}.screening-fields{display:grid;grid-template-columns:1fr 1fr;gap:8px}.screening-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.screening-result{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.manual-doc-summary{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 11px;border-radius:13px;background:#f5f2fc;margin:10px 0}.manual-doc-summary strong{font-size:12px;color:#37286f}.manual-doc-progress{font-size:11px;font-weight:900;color:#6b5ab5}.manual-doc-list{display:grid;gap:9px}.manual-doc-card{border:1px solid #e4e6ed;border-radius:14px;padding:12px;background:#fff}.manual-doc-card .doc-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.manual-doc-card .doc-name{font-size:12px;font-weight:900;color:#20283b;line-height:1.35}.manual-doc-card .doc-file{font-size:10px;color:#8a90a0;margin-top:3px;word-break:break-word}.manual-doc-card .doc-tools{display:flex;gap:8px;align-items:center;margin-top:10px;flex-wrap:wrap}.manual-doc-card .doc-tools .ops-select{flex:1;min-width:150px}.offer-flow{display:grid;gap:10px}.offer-stage-card{border:1px solid var(--line);border-radius:16px;padding:14px;background:#fff}.offer-stage-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.offer-stage-head strong{font-size:13px}.offer-stage-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.offer-mini{background:#fafafd;border:1px solid #ececf1;border-radius:11px;padding:9px}.offer-mini span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.05em;color:#969baa;font-weight:800;margin-bottom:3px}.offer-mini b{font-size:11px;line-height:1.35;word-break:break-word}.offer-links{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.offer-note{font-size:11px;color:#7d8391;line-height:1.45;margin-top:8px}
    @media(max-width:700px){.screening-fields{grid-template-columns:1fr}.screening-section{padding:12px}.screening-actions .ops-btn{flex:1 1 100%}.manual-doc-card .doc-top{display:block}.manual-doc-card .doc-tools{display:grid;grid-template-columns:1fr}.manual-doc-card .doc-tools .ops-select,.manual-doc-card .doc-tools .ops-btn,.manual-doc-card .doc-tools a{width:100%;min-width:0;text-align:center}.offer-stage-meta{grid-template-columns:1fr}.offer-links a,.offer-links button{flex:1 1 100%;text-align:center}}
'''
    s = s.replace('</style>', css + '\n  </style>', 1)

screening = r'''    function screeningControls(r){
      const aiStatus=String(r.ai?.['Status']||'AUTO PENDING').toUpperCase();
      const field=String(r.ai?.['Human Field Classification']||r.workflow?.['Field Classification']||r.screening?.['Field Classification']||r.ai?.['Field Classification']||'');
      const exp=String(r.ai?.['Human Relevant Work Experience']||r.workflow?.['Relevant Work Experience']||r.screening?.['Relevant Work Experience']||r.ai?.['Relevant Work Experience']||'');
      const manualRequired=/YES|REQUIRED/.test(String(r.workflow?.['Manual Review Required']||'').toUpperCase())||/MANUAL_REVIEW_REQUIRED/.test(String(r.workflow?.['Qualification Screening Status']||'').toUpperCase());
      const autoAction=PHASE2_BACKEND_READY?'<button class="ops-btn" onclick="retryAutoAiScreening()">Retry AI Auto</button>':'<button class="ops-btn" disabled>AI Auto · backend sync pending</button>';
      const decisionBlock=manualRequired?`<div class="screening-section"><div class="screening-result"><div><div class="screening-title">2. Confirm screening decision</div><div class="screening-help" style="margin:3px 0 0">Human decision is required for this case before it can move to SAC.</div></div><span class="badge amber">Manual decision required</span></div><select id="opsManualRecommendation" class="ops-select" style="width:100%;margin-top:10px"><option value="">Select final screening recommendation</option><option value="DIRECT_ENTRY">Direct Entry</option><option value="NORMAL_ADMISSION_SCREENING">Normal Admission</option><option value="INTERNAL_ASSESSMENT">Internal Assessment (IA)</option><option value="NOT_ELIGIBLE_CONVENTIONAL">Not Eligible - Conventional</option></select><div class="screening-actions">${PHASE2_BACKEND_READY?'<button class="ops-btn primary" onclick="completeManualScreening()">Submit Screening Decision</button>':'<button class="ops-btn" disabled>Submit Screening Decision · backend sync pending</button>'}</div></div>`:'';
      return `<div class="screening-stack"><div class="screening-section"><div class="screening-result"><div><div class="screening-title">AI Auto Screening</div><div class="screening-help" style="margin:3px 0 0">AI gets the first attempt. Manual screening remains available whenever AI is pending or requires review.</div></div><span class="badge ${classifyBadge(aiStatus)}">${esc(pretty(aiStatus))}</span></div><div class="screening-actions">${autoAction}</div></div><div class="screening-section"><div class="screening-title">1. Run manual screening</div><div class="screening-help">Confirm the relationship of the previous qualification to the applied programme and whether relevant work experience exists.</div><div class="screening-fields"><select id="opsFieldClassification" class="ops-select"><option value="">Field relationship</option><option value="RELATED" ${field==='RELATED'?'selected':''}>Related</option><option value="PARTIALLY_RELATED" ${field==='PARTIALLY_RELATED'?'selected':''}>Partially Related</option><option value="NON_RELATED" ${field==='NON_RELATED'?'selected':''}>Non-Related</option></select><select id="opsWorkExperience" class="ops-select"><option value="">Relevant work experience</option><option value="YES" ${exp==='YES'?'selected':''}>Yes</option><option value="NO" ${exp==='NO'?'selected':''}>No</option></select></div><div class="screening-actions"><button class="ops-btn primary" onclick="runQualificationScreening()">Run Manual Screening</button></div></div>${decisionBlock}</div>`;
    }
'''
s, n = re.subn(r"    function screeningControls\(r\)\{.*?\n    \}\n    // MANUAL_DOCUMENT_REVIEW_UI_V1", screening + "    // MANUAL_DOCUMENT_REVIEW_UI_V1", s, count=1, flags=re.S)
if n != 1:
    raise SystemExit('screeningControls patch failed')

manual = r'''    function manualDocumentReviewPanel(r){
      const required=requiredDocsForManual(r),files=r.files||[];
      let saved={};try{const list=JSON.parse(r.doc?.['Manual Decisions JSON']||'[]');if(Array.isArray(list))list.forEach(x=>saved[x.key]=x)}catch(_){}
      const verified=required.filter(d=>String(saved[d.key]?.status||'').toUpperCase()==='VERIFIED').length;
      const rows=required.map(d=>{const f=files.find(x=>String(x.field||'')===d.key),sv=saved[d.key]||{},value=String(sv.status||(f?'PENDING':'MISSING')).toUpperCase();const opts=f?`<option value="PENDING" ${value==='PENDING'?'selected':''}>Pending review</option><option value="VERIFIED" ${value==='VERIFIED'?'selected':''}>Verified</option><option value="NOT_ACCEPTABLE" ${value==='NOT_ACCEPTABLE'?'selected':''}>Not acceptable</option><option value="MISSING" ${value==='MISSING'?'selected':''}>Missing</option>`:`<option value="MISSING" selected>Missing</option>`;return `<div class="manual-doc-card"><div class="doc-top"><div><div class="doc-name">${esc(d.label)}</div><div class="doc-file">${f?esc(f.fileName||d.key):'No uploaded file recorded'}</div></div><span class="badge ${value==='VERIFIED'?'green':value==='NOT_ACCEPTABLE'||value==='MISSING'?'red':'amber'}">${esc(pretty(value))}</span></div><div class="doc-tools">${f?.url?`<a class="ops-btn" target="_blank" href="${esc(f.url)}">Open Document</a>`:'<button class="ops-btn" disabled>No File</button>'}<select class="ops-select manual-doc-status" data-key="${esc(d.key)}" data-label="${esc(d.label)}" onchange="updateManualDocProgress()">${opts}</select></div></div>`}).join('');
      const requiredKeys=new Set(required.map(x=>x.key)),extras=files.filter(f=>!requiredKeys.has(String(f.field||''))).map(f=>`<div class="manual-doc-card"><div class="doc-name">Additional document</div><div class="doc-file">${esc(f.fileName||f.field||'Document')}</div>${f.url?`<div class="doc-tools"><a class="ops-btn" target="_blank" href="${esc(f.url)}">Open Document</a></div>`:''}</div>`).join('');
      const submit=PHASE2_BACKEND_READY?'<button class="ops-btn primary" onclick="completeManualDocumentReview()">Submit Manual Document Review</button>':'<button class="ops-btn" disabled>Submit Manual Document Review · backend sync pending</button>';
      return `<div id="manualDocReviewPanel" style="display:none;width:100%;margin-top:12px"><div class="screening-section"><div class="screening-title">Manual Document Review</div><div class="screening-help">Open every required document and mark its review result. All required documents must be Verified before Screening can proceed.</div><div class="manual-doc-summary"><strong>Required documents</strong><span id="manualDocProgress" class="manual-doc-progress">${verified}/${required.length} verified</span></div><div class="manual-doc-list">${rows}</div>${extras?`<div style="margin-top:12px"><div class="screening-title">Additional documents</div><div class="manual-doc-list">${extras}</div></div>`:''}<textarea id="manualDocRemarks" class="ops-select" style="width:100%;min-height:76px;margin-top:12px" placeholder="Reviewer remarks (optional)"></textarea><div class="screening-actions">${submit}<button class="ops-btn" onclick="openManualDocumentReview()">Close Review</button></div></div></div>`;
    }
    function updateManualDocProgress(){const all=[...document.querySelectorAll('.manual-doc-status')],done=all.filter(x=>x.value==='VERIFIED').length,el=document.getElementById('manualDocProgress');if(el)el.textContent=`${done}/${all.length} verified`}
'''
s, n = re.subn(r"    function manualDocumentReviewPanel\(r\)\{.*?\n    \}\n    function openManualDocumentReview", manual + "    function openManualDocumentReview", s, count=1, flags=re.S)
if n != 1:
    raise SystemExit('manualDocumentReviewPanel patch failed')

helper = r'''    function renderOfferAcceptanceTab(r){
      const w=r.workflow||{},currentStage=String(w['Application Stage']||stage(r)||''),offerStatus=String(w['Offer Letter Status']||'NOT_ISSUED'),acceptanceStatus=String(w['Acceptance Status']||'NOT_OPEN');
      const eligible=['ELIGIBLE_FOR_OFFER','OFFER_ISSUED','ACCEPTANCE_PENDING','ACCEPTED'].includes(currentStage);
      const offerIssued=/ISSUED/.test(offerStatus)||['OFFER_ISSUED','ACCEPTANCE_PENDING','ACCEPTED'].includes(currentStage);
      const accepted=acceptanceStatus==='ACCEPTED'||currentStage==='ACCEPTED';
      const offerUrl=w['Offer Letter PDF URL']||'',signUrl=w['Acceptance Signing URL']||'',acceptPdf=w['Acceptance PDF URL']||'';
      return `<div class="offer-flow"><div class="offer-stage-card"><div class="offer-stage-head"><strong>6 · Offer Ready</strong><span class="badge ${eligible?'green':'amber'}">${eligible?'Ready / completed':'Waiting'}</span></div><div class="offer-stage-meta"><div class="offer-mini"><span>Application stage</span><b>${esc(pretty(currentStage||'-'))}</b></div><div class="offer-mini"><span>Offer status</span><b>${esc(pretty(offerStatus))}</b></div></div><div class="offer-note">Offer generation only becomes available after all admission gates are complete.</div></div><div class="offer-stage-card"><div class="offer-stage-head"><strong>7 · Offer Letter</strong><span class="badge ${offerIssued?'green':'amber'}">${offerIssued?'Issued':'Not issued'}</span></div><div class="offer-stage-meta"><div class="offer-mini"><span>Issued at</span><b>${esc(formatDate(w['Offer Letter Issued At']||''))}</b></div><div class="offer-mini"><span>Remarks</span><b>${esc(w['Offer Letter Remarks']||'-')}</b></div></div><div class="offer-links">${offerUrl?`<a class="ops-btn" target="_blank" href="${esc(offerUrl)}">Open Offer Letter</a>`:''}${currentStage==='ELIGIBLE_FOR_OFFER'?(PHASE2_BACKEND_READY?'<button class="ops-btn primary" onclick="issueOffer()">Generate & Send Offer</button>':'<button class="ops-btn" disabled>Generate Offer · backend sync pending</button>'):''}</div></div><div class="offer-stage-card"><div class="offer-stage-head"><strong>8 · Acceptance</strong><span class="badge ${accepted?'green':offerIssued?'amber':'blue'}">${esc(pretty(acceptanceStatus))}</span></div><div class="offer-stage-meta"><div class="offer-mini"><span>Received at</span><b>${esc(formatDate(w['Acceptance Received At']||w['Acceptance Signed At']||''))}</b></div><div class="offer-mini"><span>Signed name</span><b>${esc(w['Acceptance Signed Name']||'-')}</b></div></div><div class="offer-links">${signUrl?`<a class="ops-btn" target="_blank" href="${esc(signUrl)}">Open Acceptance Link</a>`:''}${acceptPdf?`<a class="ops-btn" target="_blank" href="${esc(acceptPdf)}">Open Acceptance PDF</a>`:''}<a class="ops-btn" target="_blank" href="/acceptance-demo.html">Preview Acceptance Page</a></div><div class="offer-note">The live acceptance link uses a secure one-time token. The preview link is visual only and does not submit student data.</div></div></div>`;
    }
'''
anchor = '    function renderDetailTabs(r){'
if 'function renderOfferAcceptanceTab(r)' not in s:
    if anchor not in s:
        raise SystemExit('renderDetailTabs anchor missing')
    s = s.replace(anchor, helper + anchor, 1)

s, n = re.subn(r"document\.getElementById\('tab-offer'\)\.innerHTML=`<div class=\"detail-grid\">.*?</div>`;const audit=", "document.getElementById('tab-offer').innerHTML=renderOfferAcceptanceTab(r);const audit=", s, count=1, flags=re.S)
if n != 1:
    raise SystemExit('offer tab replacement failed')

p.write_text(s, encoding='utf-8')
